[package]
name = "ssrust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"


[dependencies]
bytes = "1.6.0"
clap = { version = "4.5.3", features = ["derive"] }
md5 = "0.7.0"
ring = "0.17.8"
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
